// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIA0zL82qf0UMP3zrZKxsZ-yYHFvZins8',
    appId: '1:609714630718:web:6fdb188b89bc16d363216f',
    messagingSenderId: '609714630718',
    projectId: 'qurb-70667',
    authDomain: 'qurb-70667.firebaseapp.com',
    storageBucket: 'qurb-70667.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4nuCRh4_oQ9ZXzQYzCHgkzbNH1Ao2Kf8',
    appId: '1:609714630718:android:718bc6d44d9076f863216f',
    messagingSenderId: '609714630718',
    projectId: 'qurb-70667',
    storageBucket: 'qurb-70667.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeiCKIDaQS7nq5LrDSUtT3XFcz8SoiY5g',
    appId: '1:609714630718:ios:fa6fdb5ba6ab400a63216f',
    messagingSenderId: '609714630718',
    projectId: 'qurb-70667',
    storageBucket: 'qurb-70667.firebasestorage.app',
    iosClientId: '609714630718-dvjqvtsufvdug6dnh6t2bd364geooj17.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeiCKIDaQS7nq5LrDSUtT3XFcz8SoiY5g',
    appId: '1:609714630718:ios:fa6fdb5ba6ab400a63216f',
    messagingSenderId: '609714630718',
    projectId: 'qurb-70667',
    storageBucket: 'qurb-70667.firebasestorage.app',
    iosClientId: '609714630718-dvjqvtsufvdug6dnh6t2bd364geooj17.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIA0zL82qf0UMP3zrZKxsZ-yYHFvZins8',
    appId: '1:609714630718:web:b7f73d04fd98b72a63216f',
    messagingSenderId: '609714630718',
    projectId: 'qurb-70667',
    authDomain: 'qurb-70667.firebaseapp.com',
    storageBucket: 'qurb-70667.firebasestorage.app',
  );
}
